// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VanRijtDataBase.Models;

#nullable disable

namespace VanRijtDataBase.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20230906114353_v3")]
    partial class v3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("VanRijtDataBase.Model.Adres", b =>
                {
                    b.Property<int>("AdresID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("HuisNummer")
                        .HasColumnType("int");

                    b.Property<string>("PostCode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Straat")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("AdresID");

                    b.ToTable("Adres");
                });

            modelBuilder.Entity("VanRijtDataBase.Model.Evenement", b =>
                {
                    b.Property<int>("EvenementID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AdresID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Eind")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EventNaam")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("MaxBezoekers")
                        .HasColumnType("int");

                    b.Property<DateTime>("Start")
                        .HasColumnType("datetime(6)");

                    b.HasKey("EvenementID");

                    b.HasIndex("AdresID");

                    b.ToTable("Evenement");
                });

            modelBuilder.Entity("VanRijtDataBase.Model.Login", b =>
                {
                    b.Property<int>("LoginID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("LoginID");

                    b.ToTable("Login");
                });

            modelBuilder.Entity("VanRijtDataBase.Model.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("BedrijfsNaam")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("LoginID")
                        .HasColumnType("int");

                    b.Property<string>("Logo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TelefoonNummer")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("UserID");

                    b.HasIndex("LoginID");

                    b.ToTable("User");
                });

            modelBuilder.Entity("VanRijtDataBase.Model.Evenement", b =>
                {
                    b.HasOne("VanRijtDataBase.Model.Adres", "Adres")
                        .WithMany()
                        .HasForeignKey("AdresID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Adres");
                });

            modelBuilder.Entity("VanRijtDataBase.Model.User", b =>
                {
                    b.HasOne("VanRijtDataBase.Model.Login", "Login")
                        .WithMany()
                        .HasForeignKey("LoginID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Login");
                });
#pragma warning restore 612, 618
        }
    }
}
